-- Table: Seasons
CREATE TABLE Seasons (
    SeasonId INTEGER      PRIMARY KEY IDENTITY (1,1),
    Name     VARCHAR (50) 
);

-- Table: Bestiary
CREATE TABLE Bestiary (
    BestiaryId            INTEGER        PRIMARY KEY IDENTITY (1,1),
    Name                  VARCHAR (50),
    CR                    INTEGER,
    XP                    INTEGER,
    Race                  VARCHAR (50),
    Class_                 VARCHAR (50),
    Alignment             VARCHAR (50),
    Size_                  VARCHAR (20),
    Type_                  VARCHAR (100),
    SubType_               VARCHAR (100),
    Init                  INTEGER,
    Senses                VARCHAR (200),
    Aura                  VARCHAR (150),
    AC                    VARCHAR (150),
    ACMods                VARCHAR (150),
    HP                    INTEGER,
    HD                    VARCHAR (50),
    HPMods                VARCHAR (100),
    Saves                 VARCHAR (150),
    Fort                  INTEGER,
    Ref_                   INTEGER,
    Will                  INTEGER,
    SaveMods              VARCHAR (100),
    DefensiveAbilities    VARCHAR (100),
    DR                    VARCHAR (100),
    Immune                VARCHAR (200),
    Resist                VARCHAR (150),
    SR                    INTEGER,
    Weaknesses            VARCHAR (100),
    Speed                 VARCHAR (100),
    SpeedMod              VARCHAR (100),
    Melee                 VARCHAR (500),
    Ranged                VARCHAR (250),
    Space_                 VARCHAR (50),
    Reach                 VARCHAR (100),
    SpecialAttacks        VARCHAR (500),
    SpellLikeAbilities    VARCHAR (MAX),
    SpellsKnown           VARCHAR (MAX),
    SpellsPrepared        VARCHAR (MAX),
    SpellDomains          VARCHAR (50),
    AbilityScores         VARCHAR (100),
    AbilityScoreMods      VARCHAR (50),
    BaseAtk               INTEGER,
    CMB                   INTEGER,
    CMD                   INTEGER,
    Feats                 VARCHAR (MAX),
    Skills                VARCHAR (MAX),
    RacialMods            VARCHAR (250),
    Languages             VARCHAR (250),
    SQ                    VARCHAR (500),
    Environment           VARCHAR (150),
    Organization          VARCHAR (500),
    Treasure              VARCHAR (MAX),
    DescriptionVisual     VARCHAR (MAX),
    Group_              VARCHAR (50),
    IsTemplate            BIT,
    SpecialAbilities      VARCHAR (MAX),
    Gender                VARCHAR (25),
    Bloodline             VARCHAR (25),
    ProhibitedSchools     VARCHAR (50),
    BeforeCombat          VARCHAR (25),
    DuringCombat          VARCHAR (250),
    Morale                VARCHAR (150),
    Gear                  VARCHAR (250),
    OtherGear             VARCHAR (200),
    Vulnerability         VARCHAR (25),
    Note                  VARCHAR (100),
    CharacterFlag         BIT,
    CompanionFlag         BIT,
    Fly                   BIT,
    Climb                 BIT,
    Burrow                BIT,
    Swim                  BIT,
    Land                  BIT,
    TemplatesApplied      VARCHAR (50),
    OffenseNote           VARCHAR (100),
    BaseStatistics        VARCHAR (500),
    ExtractsPrepared      VARCHAR (250),
    AgeCategory           VARCHAR (25),
    DontUseRacialHD       BIT,
    VariantParent         VARCHAR (25),
    Mystery               VARCHAR (25),
    ClassArchetypes       VARCHAR (25),
    Patron                VARCHAR (25),
    CompanionFamiliarLink VARCHAR (25),
    FocusedSchool         VARCHAR (25),
    Traits                VARCHAR (25),
    AlternateNameForm     VARCHAR (50),
    StatisticsNote        VARCHAR (100),
    LinkText              VARCHAR (50),
    UniqueMonster         BIT,
    MR                    INTEGER,
    Mythic                BIT,
    MT                    INTEGER
);

-- Table: BestiaryDetail
CREATE TABLE BestiaryDetail (
    BestiaryId    INTEGER         PRIMARY KEY IDENTITY (1,1)
                                  REFERENCES Bestiary (BestiaryId),
    MonsterSource VARCHAR (100),
    Source        VARCHAR (50),
    Description   VARCHAR (MAX),
    FullText      VARCHAR (MAX) 
);

-- Table: Continents
CREATE TABLE Continents (
    ContinentId     INTEGER      PRIMARY KEY IDENTITY (1,1),
    Name            VARCHAR (50),
    IsUnderground   BIT,
    IsWater         BIT,
    PrimaryLanguage VARCHAR (50) 
);

-- Table: Feats
CREATE TABLE Feats (
    FeatId             INTEGER        PRIMARY KEY IDENTITY (1,1),
    Name               VARCHAR (50),
    Type_               VARCHAR (25),
    Description        VARCHAR (500),
    Prerequisites      VARCHAR (MAX),
    PrerequisiteFeats  VARCHAR (200),
    Benefit            VARCHAR (MAX),
    Normal             VARCHAR (500),
    Special            VARCHAR (750),
    Source             VARCHAR (50),
    Fulltext           VARCHAR (MAX),
    Teamwork           BIT,
    Critical           BIT,
    Grit               BIT,
    Style              BIT,
    Performance        BIT,
    Racial             BIT,
    CompanionFamiliar  BIT,
    RaceName           VARCHAR (50),
    Note               VARCHAR (500),
    Goal               VARCHAR (MAX),
    CompletionBenefit  VARCHAR (MAX),
    Multiples          BIT,
    SuggestedTraits    VARCHAR (100),
    PrerequisiteSkills VARCHAR (250),
    Panache            BIT,
    Betrayal           BIT,
    Targeting          BIT,
    Esoteric           BIT,
    Stare              BIT,
    WeaponMastery      BIT,
    ItemMastery        BIT,
    ArmorMastery       BIT,
    ShieldMastery      BIT,
    BloodHex           BIT
);

-- Table: MagicItems
CREATE TABLE MagicItems (
    MagicItemId     INTEGER         PRIMARY KEY IDENTITY (1,1),
    Name            VARCHAR (100),
    Aura            VARCHAR (100),
    CL              INTEGER,
    Slot            VARCHAR (50),
    Price           VARCHAR (50),
    Weight          VARCHAR (50),
    Description     VARCHAR (MAX),
    Requirements    VARCHAR (500),
    Cost            VARCHAR (150),
    Group_        VARCHAR (25),
    Source          VARCHAR (50),
    AL              VARCHAR (50),
    Int             INTEGER,
    Wis             INTEGER,
    Cha             INTEGER,
    Ego             INTEGER,
    Communication   VARCHAR (50),
    Senses          VARCHAR (100),
    Powers          VARCHAR (250),
    MagicItems      VARCHAR (250),
    FullText        VARCHAR (MAX),
    Destruction     VARCHAR (MAX),
    MinorArtifact   BIT,
    MajorArtifact   BIT,
    Abjuration      BIT,
    Conjuration     BIT,
    Divination      BIT,
    Enchantment     BIT,
    Evocation       BIT,
    Necromancy      BIT,
    Transmutation   BIT,
    AuraStrength    VARCHAR (25),
    WeightValue     FLOAT,
    PriceValue      INTEGER,
    CostValue       INTEGER,
    Languages       VARCHAR (50),
    BaseItem        VARCHAR (150),
    LinkText        VARCHAR (50),
    Mythic          BIT,
    LegendaryWeapon BIT,
    Illusion        BIT,
    Universal       BIT,
    Scaling         VARCHAR (25) 
);

-- Table: MonsterSpawns
CREATE TABLE MonsterSpawns (
    SpawnId    INTEGER PRIMARY KEY IDENTITY (1,1),
    Continent  INTEGER REFERENCES Continents (ContinentId),
    Season     INTEGER REFERENCES Seasons (SeasonId),
    BestiaryId INTEGER REFERENCES Bestiary (BestiaryId) 
);

-- Table: Months
CREATE TABLE Months (
    MonthId INTEGER      PRIMARY KEY IDENTITY (1,1),
    Name    VARCHAR (50),
    Season  INTEGER      REFERENCES Seasons (SeasonId),
    Days    INTEGER
);

-- Table: NPCs
CREATE TABLE NPCs (
    NPCID                      INTEGER        PRIMARY KEY IDENTITY (1,1),
    Name                       VARCHAR (100),
    CR                         INTEGER,
    XP                         INTEGER,
    Race                       VARCHAR (100),
    Class_                      VARCHAR (100),
    Alignment                  VARCHAR (25),
    Size_                       VARCHAR (25),
    Type_                       VARCHAR (50),
    SubType_                    VARCHAR (100),
    Init                       INTEGER,
    Senses                     VARCHAR (150),
    Aura                       VARCHAR (150),
    AC                         VARCHAR (50),
    ACMods                     VARCHAR (150),
    HP                         INTEGER,
    HD                         VARCHAR (100),
    HPMods                     VARCHAR (100),
    Saves                      VARCHAR (200),
    Fort                       INTEGER,
    Ref_                        INTEGER,
    Will                       INTEGER,
    SaveMods                   VARCHAR (150),
    DefensiveAbilities         VARCHAR (200),
    DR                         VARCHAR (100),
    Immune                     VARCHAR (250),
    Resist                     VARCHAR (100),
    SR                         VARCHAR (50),
    Weaknesses                 VARCHAR (100),
    Speed                      VARCHAR (100),
    SpeedMod                   VARCHAR (100),
    Melee                      VARCHAR (500),
    Ranged                     VARCHAR (250),
    Space_                      VARCHAR (25),
    Reach                      VARCHAR (50),
    SpecialAttacks             VARCHAR (500),
    SpellLikeAbilities         VARCHAR (700),
    SpellsKnown                VARCHAR (MAX),
    SpellsPrepared             VARCHAR (MAX),
    SpellDomains               VARCHAR (100),
    AbilityScores              VARCHAR (100),
    AbilityScoreMods           VARCHAR (25),
    BaseAtk                    INTEGER,
    CMB                        INTEGER,
    CMD                        INTEGER,
    Feats                      VARCHAR (MAX),
    Skills                     VARCHAR (MAX),
    RacialMods                 VARCHAR (200),
    Languages                  VARCHAR (500),
    SQ                         VARCHAR (500),
    Environment                VARCHAR (25),
    Treasure                   VARCHAR (25),
    Organization               VARCHAR (25),
    DescriptionVisual          VARCHAR (150),
    Group_                   VARCHAR (25),
    Source                     VARCHAR (50),
    IsTemplate                 BIT,
    SpecialAbilities           VARCHAR (MAX),
    Gender                     VARCHAR (25),
    Bloodline                  VARCHAR (50),
    ProhibitedSchools          VARCHAR (50),
    BeforeCombat               VARCHAR (MAX),
    DuringCombat               VARCHAR (MAX),
    Morale                     VARCHAR (MAX),
    Gear                       VARCHAR (MAX),
    OtherGear                  VARCHAR (MAX),
    Vulnerability              VARCHAR (25),
    Note                       VARCHAR (250),
    CharacterFlag              BIT,
    CompanionFlag              BIT,
    Fly                        BIT,
    Climb                      BIT,
    Burrow                     BIT,
    Swim                       BIT,
    Land                       BIT,
    TemplatesApplied           VARCHAR (50),
    OffenseNote                VARCHAR (150),
    BaseStatistics             VARCHAR (MAX),
    ExtractsPrepared           VARCHAR (500),
    AgeCategory                VARCHAR (25),
    Mystery                    VARCHAR (100),
    ClassArchetypes            VARCHAR (100),
    Patron                     VARCHAR (50),
    CompanionFamiliarLink      VARCHAR (25),
    FocusedSchool              VARCHAR (25),
    Traits                     VARCHAR (100),
    AlternateNameForm          VARCHAR (50),
    LinkText                   VARCHAR (50),
    UniqueMonster              BIT,
    ThassilonianSpecialization VARCHAR (50),
    Variant                    BIT,
    MR                         INTEGER,
    Mythic                     BIT,
    MT                         INTEGER,
    Spirit                     VARCHAR (25),
    PsychicMagic               VARCHAR (25),
    KineticistWildTalents      VARCHAR (500),
    Implements                 VARCHAR (MAX),
    PsychicDiscipline          VARCHAR (25) 
);



-- Table: Spells
CREATE TABLE Spells (
    SpellId           INTEGER        PRIMARY KEY IDENTITY (1,1),
    Name              VARCHAR (50),
    School            VARCHAR (25),
    SubSchool         VARCHAR (25),
    Descriptor        VARCHAR (50),
    SpellLevel        VARCHAR (200),
    CastingTime       VARCHAR (50),
    Components        VARCHAR (200),
    CostlyComponents  BIT,
    Range             VARCHAR (100),
    Area              VARCHAR (100),
    Effect            VARCHAR (200),
    Targets           VARCHAR (200),
    Duration          VARCHAR (100),
    Dismissable       BIT,
    Shapeable         BIT,
    SavingThrow       VARCHAR (100),
    SpellResistance   VARCHAR (50),
    Source            VARCHAR (50),
    Verbal            BIT,
    Somatic           BIT,
    Material          BIT,
    Focus             BIT,
    DivineFocus       BIT,
    Sor               INTEGER,
    Wiz               INTEGER,
    Cleric            INTEGER,
    Druid             INTEGER,
    Ranger            INTEGER,
    Bard              INTEGER,
    Paladin           INTEGER,
    Alchemist         INTEGER,
    Summoner          INTEGER,
    Witch             INTEGER,
    Inquisitor        INTEGER,
    Oracle            INTEGER,
    Antipaladin       INTEGER,
    Magus             INTEGER,
    Adept             INTEGER,
    Deity             VARCHAR (25),
    SLALevel          INTEGER,
    Domain            VARCHAR (100),
    ShortDescription  VARCHAR (250),
    Acid              BIT,
    Air               BIT,
    Chaotic           BIT,
    Cold              BIT,
    Curse             BIT,
    Darkness          BIT,
    Death             BIT,
    Disease           BIT,
    Earth             BIT,
    Electricity       BIT,
    Emotion           BIT,
    Evil              BIT,
    Fear              BIT,
    Fire              BIT,
    Force             BIT,
    Good              BIT,
    LanguageDependent BIT,
    Lawful            BIT,
    Light             BIT,
    MindAffecting     BIT,
    Pain              BIT,
    Poison            BIT,
    Shadow            BIT,
    Sonic             BIT,
    Water             BIT,
    LinkText          VARCHAR (50),
    MaterialCost      INTEGER,
    Bloodline         VARCHAR (150),
    Patron            VARCHAR (100),
    MythicText        VARCHAR (MAX),
    Augmented         VARCHAR (500),
    Mythic            BIT,
    BloodRager        INTEGER,
    Shaman            INTEGER,
    Psychic           INTEGER,
    Medium            INTEGER,
    Mesmerist         INTEGER,
    Occultist         INTEGER,
    Spiritualist      INTEGER,
    Skald             INTEGER,
    Investigator      INTEGER,
    Hunter            INTEGER,
    HauntStatistics   VARCHAR (250) 
);


-- Table: NPCDetails
CREATE TABLE NPCDetails (
    NPCID         INTEGER         PRIMARY KEY IDENTITY (1,1)
                                  REFERENCES NPCs (NPCID) ,
    MonsterSource VARCHAR (250),
    Description   VARCHAR (MAX),
    FullText      VARCHAR (MAX) 
);



-- Table: SpellDetails
CREATE TABLE SpellDetails (
    SpellId              INTEGER         PRIMARY KEY IDENTITY (1,1)
                                         REFERENCES Spells (SpellId) ,
    Description          VARCHAR (MAX),
    DescriptionFormatted VARCHAR (MAX),
    FullText             VARCHAR (MAX) 
);