//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pathfinder_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestiary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bestiary()
        {
            this.MonsterSpawns = new HashSet<MonsterSpawn>();
        }
    
        public int BestiaryId { get; set; }
        public string Name { get; set; }
        public Nullable<int> CR { get; set; }
        public Nullable<int> XP { get; set; }
        public string Race { get; set; }
        public string Class_ { get; set; }
        public string Alignment { get; set; }
        public string Size_ { get; set; }
        public string Type_ { get; set; }
        public string SubType_ { get; set; }
        public Nullable<int> Init { get; set; }
        public string Senses { get; set; }
        public string Aura { get; set; }
        public string AC { get; set; }
        public string ACMods { get; set; }
        public Nullable<int> HP { get; set; }
        public string HD { get; set; }
        public string HPMods { get; set; }
        public string Saves { get; set; }
        public Nullable<int> Fort { get; set; }
        public Nullable<int> Ref_ { get; set; }
        public Nullable<int> Will { get; set; }
        public string SaveMods { get; set; }
        public string DefensiveAbilities { get; set; }
        public string DR { get; set; }
        public string Immune { get; set; }
        public string Resist { get; set; }
        public Nullable<int> SR { get; set; }
        public string Weaknesses { get; set; }
        public string Speed { get; set; }
        public string SpeedMod { get; set; }
        public string Melee { get; set; }
        public string Ranged { get; set; }
        public string Space_ { get; set; }
        public string Reach { get; set; }
        public string SpecialAttacks { get; set; }
        public string SpellLikeAbilities { get; set; }
        public string SpellsKnown { get; set; }
        public string SpellsPrepared { get; set; }
        public string SpellDomains { get; set; }
        public string AbilityScores { get; set; }
        public string AbilityScoreMods { get; set; }
        public Nullable<int> BaseAtk { get; set; }
        public Nullable<int> CMB { get; set; }
        public Nullable<int> CMD { get; set; }
        public string Feats { get; set; }
        public string Skills { get; set; }
        public string RacialMods { get; set; }
        public string Languages { get; set; }
        public string SQ { get; set; }
        public string Environment { get; set; }
        public string Organization { get; set; }
        public string Treasure { get; set; }
        public string DescriptionVisual { get; set; }
        public string Group_ { get; set; }
        public Nullable<bool> IsTemplate { get; set; }
        public string SpecialAbilities { get; set; }
        public string Gender { get; set; }
        public string Bloodline { get; set; }
        public string ProhibitedSchools { get; set; }
        public string BeforeCombat { get; set; }
        public string DuringCombat { get; set; }
        public string Morale { get; set; }
        public string Gear { get; set; }
        public string OtherGear { get; set; }
        public string Vulnerability { get; set; }
        public string Note { get; set; }
        public Nullable<bool> CharacterFlag { get; set; }
        public Nullable<bool> CompanionFlag { get; set; }
        public Nullable<bool> Fly { get; set; }
        public Nullable<bool> Climb { get; set; }
        public Nullable<bool> Burrow { get; set; }
        public Nullable<bool> Swim { get; set; }
        public Nullable<bool> Land { get; set; }
        public string TemplatesApplied { get; set; }
        public string OffenseNote { get; set; }
        public string BaseStatistics { get; set; }
        public string ExtractsPrepared { get; set; }
        public string AgeCategory { get; set; }
        public Nullable<bool> DontUseRacialHD { get; set; }
        public string VariantParent { get; set; }
        public string Mystery { get; set; }
        public string ClassArchetypes { get; set; }
        public string Patron { get; set; }
        public string CompanionFamiliarLink { get; set; }
        public string FocusedSchool { get; set; }
        public string Traits { get; set; }
        public string AlternateNameForm { get; set; }
        public string StatisticsNote { get; set; }
        public string LinkText { get; set; }
        public Nullable<bool> UniqueMonster { get; set; }
        public Nullable<int> MR { get; set; }
        public Nullable<bool> Mythic { get; set; }
        public Nullable<int> MT { get; set; }
    
        public virtual BestiaryDetail BestiaryDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonsterSpawn> MonsterSpawns { get; set; }
    }
}
