//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pathfinder_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContinentWeather
    {
        public int CWID { get; set; }
        public int ContinentId { get; set; }
        public int WeatherId { get; set; }
        public int SeasonId { get; set; }
        public int ExtraWeight { get; set; }
    }
}
