//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pathfinder_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feat
    {
        public int FeatId { get; set; }
        public string Name { get; set; }
        public string Type_ { get; set; }
        public string Description { get; set; }
        public string Prerequisites { get; set; }
        public string PrerequisiteFeats { get; set; }
        public string Benefit { get; set; }
        public string Normal { get; set; }
        public string Special { get; set; }
        public string Source { get; set; }
        public string Fulltext { get; set; }
        public Nullable<bool> Teamwork { get; set; }
        public Nullable<bool> Critical { get; set; }
        public Nullable<bool> Grit { get; set; }
        public Nullable<bool> Style { get; set; }
        public Nullable<bool> Performance { get; set; }
        public Nullable<bool> Racial { get; set; }
        public Nullable<bool> CompanionFamiliar { get; set; }
        public string RaceName { get; set; }
        public string Note { get; set; }
        public string Goal { get; set; }
        public string CompletionBenefit { get; set; }
        public Nullable<bool> Multiples { get; set; }
        public string SuggestedTraits { get; set; }
        public string PrerequisiteSkills { get; set; }
        public Nullable<bool> Panache { get; set; }
        public Nullable<bool> Betrayal { get; set; }
        public Nullable<bool> Targeting { get; set; }
        public Nullable<bool> Esoteric { get; set; }
        public Nullable<bool> Stare { get; set; }
        public Nullable<bool> WeaponMastery { get; set; }
        public Nullable<bool> ItemMastery { get; set; }
        public Nullable<bool> ArmorMastery { get; set; }
        public Nullable<bool> ShieldMastery { get; set; }
        public Nullable<bool> BloodHex { get; set; }
    }
}
