//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pathfinder_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class MagicItem
    {
        public int MagicItemId { get; set; }
        public string Name { get; set; }
        public string Aura { get; set; }
        public Nullable<int> CL { get; set; }
        public string Slot { get; set; }
        public string Price { get; set; }
        public string Weight { get; set; }
        public string Description { get; set; }
        public string Requirements { get; set; }
        public string Cost { get; set; }
        public string Group_ { get; set; }
        public string Source { get; set; }
        public string AL { get; set; }
        public Nullable<int> Int { get; set; }
        public Nullable<int> Wis { get; set; }
        public Nullable<int> Cha { get; set; }
        public Nullable<int> Ego { get; set; }
        public string Communication { get; set; }
        public string Senses { get; set; }
        public string Powers { get; set; }
        public string MagicItems { get; set; }
        public string FullText { get; set; }
        public string Destruction { get; set; }
        public Nullable<bool> MinorArtifact { get; set; }
        public Nullable<bool> MajorArtifact { get; set; }
        public Nullable<bool> Abjuration { get; set; }
        public Nullable<bool> Conjuration { get; set; }
        public Nullable<bool> Divination { get; set; }
        public Nullable<bool> Enchantment { get; set; }
        public Nullable<bool> Evocation { get; set; }
        public Nullable<bool> Necromancy { get; set; }
        public Nullable<bool> Transmutation { get; set; }
        public string AuraStrength { get; set; }
        public Nullable<double> WeightValue { get; set; }
        public Nullable<int> PriceValue { get; set; }
        public Nullable<int> CostValue { get; set; }
        public string Languages { get; set; }
        public string BaseItem { get; set; }
        public string LinkText { get; set; }
        public Nullable<bool> Mythic { get; set; }
        public Nullable<bool> LegendaryWeapon { get; set; }
        public Nullable<bool> Illusion { get; set; }
        public Nullable<bool> Universal { get; set; }
        public string Scaling { get; set; }
    }
}
