//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pathfinder_Helper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PFDBEntities : DbContext
    {
        public PFDBEntities()
            : base("name=PFDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bestiary> Bestiaries { get; set; }
        public virtual DbSet<BestiaryDetail> BestiaryDetails { get; set; }
        public virtual DbSet<Continent> Continents { get; set; }
        public virtual DbSet<Faction> Factions { get; set; }
        public virtual DbSet<Feat> Feats { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MagicItem> MagicItems { get; set; }
        public virtual DbSet<MonsterSpawn> MonsterSpawns { get; set; }
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<NPCDetail> NPCDetails { get; set; }
        public virtual DbSet<NPC> NPCs { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<SpellDetail> SpellDetails { get; set; }
        public virtual DbSet<Spell> Spells { get; set; }
        public virtual DbSet<TEMP_SpellDetails> TEMP_SpellDetails { get; set; }
        public virtual DbSet<Territory> Territories { get; set; }
        public virtual DbSet<ContinentWeather> ContinentWeathers { get; set; }
        public virtual DbSet<Weather> Weathers { get; set; }
    }
}
