//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pathfinder_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spell
    {
        public int SpellId { get; set; }
        public string Name { get; set; }
        public string School { get; set; }
        public string SubSchool { get; set; }
        public string Descriptor { get; set; }
        public string SpellLevel { get; set; }
        public string CastingTime { get; set; }
        public string Components { get; set; }
        public Nullable<bool> CostlyComponents { get; set; }
        public string Range { get; set; }
        public string Area { get; set; }
        public string Effect { get; set; }
        public string Targets { get; set; }
        public string Duration { get; set; }
        public Nullable<bool> Dismissable { get; set; }
        public Nullable<bool> Shapeable { get; set; }
        public string SavingThrow { get; set; }
        public string SpellResistance { get; set; }
        public string Source { get; set; }
        public Nullable<bool> Verbal { get; set; }
        public Nullable<bool> Somatic { get; set; }
        public Nullable<bool> Material { get; set; }
        public Nullable<bool> Focus { get; set; }
        public Nullable<bool> DivineFocus { get; set; }
        public Nullable<int> Sor { get; set; }
        public Nullable<int> Wiz { get; set; }
        public Nullable<int> Cleric { get; set; }
        public Nullable<int> Druid { get; set; }
        public Nullable<int> Ranger { get; set; }
        public Nullable<int> Bard { get; set; }
        public Nullable<int> Paladin { get; set; }
        public Nullable<int> Alchemist { get; set; }
        public Nullable<int> Summoner { get; set; }
        public Nullable<int> Witch { get; set; }
        public Nullable<int> Inquisitor { get; set; }
        public Nullable<int> Oracle { get; set; }
        public Nullable<int> Antipaladin { get; set; }
        public Nullable<int> Magus { get; set; }
        public Nullable<int> Adept { get; set; }
        public string Deity { get; set; }
        public Nullable<int> SLALevel { get; set; }
        public string Domain { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<bool> Acid { get; set; }
        public Nullable<bool> Air { get; set; }
        public Nullable<bool> Chaotic { get; set; }
        public Nullable<bool> Cold { get; set; }
        public Nullable<bool> Curse { get; set; }
        public Nullable<bool> Darkness { get; set; }
        public Nullable<bool> Death { get; set; }
        public Nullable<bool> Disease { get; set; }
        public Nullable<bool> Earth { get; set; }
        public Nullable<bool> Electricity { get; set; }
        public Nullable<bool> Emotion { get; set; }
        public Nullable<bool> Evil { get; set; }
        public Nullable<bool> Fear { get; set; }
        public Nullable<bool> Fire { get; set; }
        public Nullable<bool> Force { get; set; }
        public Nullable<bool> Good { get; set; }
        public Nullable<bool> LanguageDependent { get; set; }
        public Nullable<bool> Lawful { get; set; }
        public Nullable<bool> Light { get; set; }
        public Nullable<bool> MindAffecting { get; set; }
        public Nullable<bool> Pain { get; set; }
        public Nullable<bool> Poison { get; set; }
        public Nullable<bool> Shadow { get; set; }
        public Nullable<bool> Sonic { get; set; }
        public Nullable<bool> Water { get; set; }
        public string LinkText { get; set; }
        public Nullable<int> MaterialCost { get; set; }
        public string Bloodline { get; set; }
        public string Patron { get; set; }
        public string MythicText { get; set; }
        public string Augmented { get; set; }
        public Nullable<bool> Mythic { get; set; }
        public Nullable<int> BloodRager { get; set; }
        public Nullable<int> Shaman { get; set; }
        public Nullable<int> Psychic { get; set; }
        public Nullable<int> Medium { get; set; }
        public Nullable<int> Mesmerist { get; set; }
        public Nullable<int> Occultist { get; set; }
        public Nullable<int> Spiritualist { get; set; }
        public Nullable<int> Skald { get; set; }
        public Nullable<int> Investigator { get; set; }
        public Nullable<int> Hunter { get; set; }
        public string HauntStatistics { get; set; }
    
        public virtual SpellDetail SpellDetail { get; set; }
    }
}
