//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pathfinder_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpellDetail
    {
        public int SpellId { get; set; }
        public string Description { get; set; }
        public string DescriptionFormatted { get; set; }
        public string FullText { get; set; }
    
        public virtual Spell Spell { get; set; }
    }
}
