//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pathfinder_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Territory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Territory()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public int TerritoryId { get; set; }
        public Nullable<int> ContinentId { get; set; }
        public Nullable<int> Factionid { get; set; }
        public string Name { get; set; }
    
        public virtual Continent Continent { get; set; }
        public virtual Faction Faction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Locations { get; set; }
    }
}
